# --- !Ups

CREATE TABLE "user" (
  userID varchar NOT NULL,
  firstName varchar,
  lastName varchar,
  fullName varchar,
  email varchar,
  PRIMARY KEY (userID)
);

CREATE TABLE passwordinfo (
  hasher varchar NOT NULL,
  password varchar NOT NULL,
  userID varchar NOT NULL
);

CREATE TABLE logininfo (
  userID varchar NOT NULL,
  providerID varchar NOT NULL,
  providerKey varchar NOT NULL,
  PRIMARY KEY (userID)
);

-- CREATE TABLE userlogininfo (
--   userID varchar NOT NULL,
--   loginInfoId bigint NOT NULL
-- );

-- create table "oauth1info" ("id" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL PRIMARY KEY,"token" VARCHAR NOT NULL,"secret" VARCHAR NOT NULL,"loginInfoId" BIGINT NOT NULL);
-- create table "oauth2info" ("id" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL PRIMARY KEY,"accesstoken" VARCHAR NOT NULL,"tokentype" VARCHAR,"expiresin" INTEGER,"refreshtoken" VARCHAR,"logininfoid" BIGINT NOT NULL);
-- create table "openidinfo" ("id" VARCHAR NOT NULL PRIMARY KEY,"logininfoid" BIGINT NOT NULL);
-- create table "openidattributes" ("id" VARCHAR NOT NULL,"key" VARCHAR NOT NULL,"value" VARCHAR NOT NULL);


# --- !Downs

-- drop table "passwordinfo";
-- drop table "userlogininfo";
-- drop table "logininfo";
-- drop table "user";